// Generated by CoffeeScript 1.9.1
cc.game.onStart = function() {
  cc.view.adjustViewPort(true);
  cc.view.setDesignResolutionSize(720, 1280, cc.ResolutionPolicy.SHOW_ALL);
  cc.view.resizeWithBrowserSize(true);
  return cc.LoaderScene.preload(g_resources, function() {
    cc.spriteFrameCache.addSpriteFrames(res.atlas_game_plist);
    return cc.director.runScene(new app.scene);
  }, this);
};

cc.game.run();
