// Generated by CoffeeScript 1.9.1
UI = {};
UI.btnListener = function() {
  return cc.EventListener.create({
    event: cc.EventListener.TOUCH_ONE_BY_ONE,
    swallowTouches: true,
    onTouchBegan: function(touch, event) {
      var locationInNode, rect, size, spr, target;
      target = event.getCurrentTarget();
      spr = target.btnSpr;
      locationInNode = spr.convertToNodeSpace(touch.getLocation());
      size = spr.getContentSize();
      rect = cc.rect(0, 0, size.width, size.height);
      if (cc.rectContainsPoint(rect, locationInNode)) {
        target.fadeEff();
        return true;
      } else {
        return false;
      }
    },
    onTouchEnded: function(touch, event) {
      var target;
      target = event.getCurrentTarget();
      return target.eventTouch.invoke();
    }
  });
};

UI.createButton = function(pic, pos) {
  var btn;
  btn = new cc.Layer();
  btn.btnSpr = new cc.Sprite(pic);
  btn.eventTouch = Utils.event_0();
  btn.btnSpr.x = pos.x;
  btn.btnSpr.y = pos.y;
  btn.addChild(btn.btnSpr);
  btn.btnEff = new cc.Sprite("#circle.png");
  btn.btnEff.x = pos.x;
  btn.btnEff.y = pos.y;
  btn.btnEff.opacity = 0;
  btn.fadeEff = function() {
    var fade;
    this.btnEff.opacity = 255;
    fade = cc.fadeOut(0.4);
    fade.easing(cc.easeQuadraticActionIn());
    return this.btnEff.runAction(fade);
  };
  btn.addChild(btn.btnEff);
  btn.listener = UI.btnListener();
  cc.eventManager.addListener(btn.listener, btn);
  return btn;
};

UI.createIndex = function(index) {
  var delt, interval, layer;
  delt = 40;
  interval = 0.3;
  layer = new cc.Layer();
  layer.curIndex = index;
  layer.curInd = new cc.LabelTTF(index.toString(), 'aaargh', 72);
  layer.curInd.setFontFillColor(cc.color(64, 86, 99, 255));
  layer.curInd.x = 360;
  layer.curInd.y = 1190;
  layer.lastInd = new cc.LabelTTF(index.toString(), 'aaargh', 72);
  layer.lastInd.setFontFillColor(cc.color(64, 86, 99, 255));
  layer.lastInd.x = 360 - delt;
  layer.lastInd.y = 1190;
  layer.lastInd.opacity = 0;

  /*
  layer.instruction = new cc.LabelTTF('Touch the central red', 'aaargh', 54)
  layer.instruction.setFontFillColor(cc.color(64, 86, 99, 255))
  layer.instruction.x = 360
  layer.instruction.y = 1280 - 320
  layer.instruction.opacity = 0
   */
  layer.addChild(layer.curInd);
  layer.addChild(layer.lastInd);
  layer.changeIndex = function(_index, cb) {
    var fadeIn, fadeOut, moveIn, moveOut;
    this.lastInd.setString(this.curIndex.toString());
    this.lastInd.x = 360;
    this.lastInd.y = 1190;
    this.lastInd.opacity = 255;
    this.curInd.setString(_index.toString());
    this.curInd.x = 360 + delt;
    this.curInd.y = 1190;
    this.curInd.opacity = 0;
    this.curIndex = _index;
    moveOut = cc.moveTo(interval, cc.p(360 - delt, 1190));
    moveOut.easing(cc.easeQuadraticActionIn());
    fadeOut = cc.fadeOut(interval);
    fadeOut.easing(cc.easeQuadraticActionIn());
    moveIn = cc.moveTo(interval, cc.p(360, 1190));
    moveIn.easing(cc.easeQuadraticActionOut());
    fadeIn = cc.fadeIn(interval);
    fadeIn.easing(cc.easeQuadraticActionOut());
    this.lastInd.runAction(moveOut);
    this.lastInd.runAction(fadeOut);
    this.curInd.runAction(moveIn);
    return this.curInd.runAction(fadeIn);
  };
  return layer;
};

UI.createUI = function(leftCb, refreshCb, rightCb) {
  var ui;
  ui = new cc.Layer();
  ui.left = UI.createButton("#left.png", cc.p(64, 80));
  ui.left.eventTouch.add(leftCb);
  ui.refresh = UI.createButton("#refresh.png", cc.p(360, 80));
  ui.refresh.eventTouch.add(refreshCb);
  ui.right = UI.createButton("#right.png", cc.p(720 - 64, 80));
  ui.right.eventTouch.add(rightCb);
  ui.index = UI.createIndex(1);
  ui.addChild(ui.left);
  ui.addChild(ui.refresh);
  ui.addChild(ui.right);
  ui.addChild(ui.index);
  ui.changeIndex = function(index) {
    return ui.index.changeIndex(index);
  };
  return ui;
};
